<a href="https://colab.research.google.com/github/presidentlines/CS472FinalProject/blob/main/speech_phonemes_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!apt-get install -y swig libpulse-dev
!apt-get install ffmpeg


Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libpulse-mainloop-glib0 swig3.0
Suggested packages:
  swig-doc swig-examples swig3.0-examples swig3.0-doc
The following NEW packages will be installed:
  libpulse-dev libpulse-mainloop-glib0 swig swig3.0
0 upgraded, 4 newly installed, 0 to remove and 31 not upgraded.
Need to get 1,204 kB of archives.
After this operation, 6,540 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpulse-mainloop-glib0 amd64 1:11.1-1ubuntu7.11 [22.1 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 libpulse-dev amd64 1:11.1-1ubuntu7.11 [81.5 kB]
Get:3 http://archive.ubuntu.com/ubuntu bionic/universe amd64 swig3.0 amd64 3.0.12-1 [1,094 kB]
Get:4 http://archive.ubuntu.com/ubuntu bionic/universe amd64 swig amd64 3.0.12-1 [6,460 B]
Fetched 1,204 kB in 1s (1,173 kB/s)
Selecting previous

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# !git init
# !git remote add origin https://presidentlines:horseracetrack1@github.com/presidentlines/CS472FinalProject.git

# !git config --global user.email “presidentlines@gmail.com”
# !git config --global user.name "presidentlines"
!git add "/content/drive/My\ Drive/"
!git commit -m “first commit”

!git push -u origin master



Mounted at /content/drive
error: open("drive/MyDrive/2020 Calendar.gsheet"): Operation not supported
error: unable to index file drive/MyDrive/2020 Calendar.gsheet
fatal: adding files failed
error: pathspec 'commit”' did not match any file(s) known to git.
error: src refspec master does not match any.
error: failed to push some refs to 'https://github.com/presidentlines/CS472FinalProject.git'


# New Section

In [ ]:
#https://commonvoice.mozilla.org/en/datasets
#our dataset

In [ ]:
!apt-get install libsox-fmt-all libsox-dev sox > /dev/null
! python -m pip install torchaudio > /dev/null
! python -m pip install git+https://github.com/facebookresearch/WavAugment.git > /dev/null

  Running command git clone -q https://github.com/facebookresearch/WavAugment.git /tmp/pip-req-build-i2vpl69r


In [ ]:
!pip install pocketsphinx


     |████████████████████████████████| 29.1MB 124kB/s 
  Created wheel for pocketsphinx: filename=pocketsphinx-0.1.15-cp37-cp37m-linux_x86_64.whl size=30127553 sha256=a956feed2223660a6fe58ec6219d04753df791053b0eed9f396725cb7c78eebd
  Stored in directory: /root/.cache/pip/wheels/52/fd/52/2f62c9a0036940cc0c89e58ee0b9d00fcf78243aeaf416265f
Successfully built pocketsphinx


In [ ]:
#https://www.rubydoc.info/gems/pocketsphinx-ruby/Pocketsphinx/Decoder
#Doc Specs Pocketsphinx

from pocketsphinx.pocketsphinx import *
from sphinxbase.sphinxbase import *
from os import environ, path

#Need to set model and test directory

config = Decoder.default_config()


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Danny_spanish.m4a to Danny_spanish.m4a
Saving Domo_arigoto.m4a to Domo_arigoto.m4a
Saving English_test.m4a to English_test.m4a
Saving La Playa.m4a to La Playa.m4a
Saving N 300 E St.m4a to N 300 E St.m4a
Saving rockford_beach.m4a to rockford_beach.m4a
Saving Rockford_spanish.m4a to Rockford_spanish.m4a
Saving Sam Spanish.m4a to Sam Spanish.m4a


In [ ]:
file = "/content/drive/My\ Drive/test/file88.flac"

# # #changes to pcm
# # !ffmpeg -i alphabet.m4a -f s16le -acodec pcm_s16le alphabet.pcm

# #changes to wav
!ffmpeg -i La\ Playa.m4a -acodec pcm_s16le -ac 1 -ar 16000 playa.wav
!ffmpeg -i alphabet.m4a -acodec pcm_s16le -ac 1 -ar 16000 alphabet.wav

# !ffmpeg -i $file -acodec pcm_s16le -ac 1 -ar 16000 common_voice.wav



ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lib

In [ ]:
!pip install -U -q PyDrive
import os
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# 1. Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

# choose a local (colab) directory to store the data.
local_download_path = os.path.expanduser('~/data')
try:
  os.makedirs(local_download_path)
except: pass

# 2. Auto-iterate using the query syntax
#    https://developers.google.com/drive/v2/web/search-parameters
spanish_audio = drive.ListFile(
    {'q': "'1IBsBoEl7cOri-HmUzOAid4f9PIgU0DxX' in parents"}).GetList()
english_audio = drive.ListFile(
    {'q': "'1Jplbe08q4tRZK5PfReyLOJiqv09vX0fb' in parents"}).GetList()
german_audio = drive.ListFile(
    {'q': "'1guWw707ACfWqY1nZUC5MtLWT1FRuNrFf' in parents"}).GetList()
japanese_audio = drive.ListFile(
    {'q': "'13IqtcnfS1CGGaV50UHhLNioofIjXcb9A' in parents"}).GetList()
thai_audio = drive.ListFile(
    {'q': "'1tbirRw-xVMlWl9vgdSVakMdZTHc21oAV' in parents"}).GetList()
  

list_files = list()
list_f_ = list()


In [ ]:
# print(list_files)
# print(list_f_)
# print(file_list)

def print_audio_names(audio):
  for f in audio:
  print(f['title'])

print_audio_names(spanish_audio)
print_audio_names(english_audio)
print_audio_names(german_audio)
print_audio_names(japanese_audio)
print_audio_names(thai_audio)


es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment87.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment82.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment89.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment84.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment86.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment81.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment80.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment90.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment8.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment85.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment9.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment79.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment77.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment71.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment78.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment74.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment73.flac
es_m_08111ce8d6a7ebc6cd2c27e62a3d98f0.fragment72.flac
es_m_08111ce8d6a7ebc6cd2c27e62

In [ ]:


#This guy checks what the status of the file is

# !sox --i "playa.wav"
spanish_names = ["/content/drive/My\ Drive/test/spanish/" + str(f['title']) for f in spanish_audio]
english_names = ["/content/drive/My\ Drive/test/english/" + str(f['title']) for f in english_audio]
german_names = ["/content/drive/My\ Drive/test/german/" + str(f['title']) for f in german_audio]
japanese_names = ["/content/drive/My\ Drive/test/japanese/" + str(f['title']) for f in japanese_audio]
thai_names = ["/content/drive/My\ Drive/test/thai/" + str(f['title']) for f in thai_audio]

def convert_to_wav(wav_list, added_num):
  total_list = list()
  for i, old_wav in enumerate(wav_list):
    name = str(i + added_num) + ".wav"
    !ffmpeg -i $old_wav -acodec pcm_s16le -ac 1 -ar 16000 $name
    total_list.append(name)
  return total_list

#this takes FOREVER to run :P also, you may need to change the indices
spanish_list = convert_to_wav(spanish_names, 2000)
english_list = convert_to_wav(english_names, 2400)
german_list = convert_to_wav(german_names, 2800)
japanese_list = convert_to_wav(japanese_names[-180:], 3400)
thai_list = convert_to_wav(thai_names[-180:], 3600)

# thai_list = list()
# for i, old_wav in enumerate(thai_names[-180:]):
#   name = str(i + 3800) + ".wav"
#   !ffmpeg -i $old_wav -acodec pcm_s16le -ac 1 -ar 16000 $name
#   thai_list.append(name)

Streaming output truncated to the last 5000 lines.
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
    Metadata:
      encoder         : Lavc57.107.100 pcm_s16le
size=      95kB time=00:00:03.02 bitrate= 256.2kbits/s speed= 547x    
video:0kB audio:94kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.080605%
ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enab

In [ ]:
#prints out all the wavs in our list of wav names

# for name in new_wav_names:
#   !sox --i $name

print(spanish_list)
print(english_list)
print(german_list)
print(japanese_list)
print(thai_list)


['2000.wav', '2001.wav', '2002.wav', '2003.wav', '2004.wav', '2005.wav', '2006.wav', '2007.wav', '2008.wav', '2009.wav', '2010.wav', '2011.wav', '2012.wav', '2013.wav', '2014.wav', '2015.wav', '2016.wav', '2017.wav', '2018.wav', '2019.wav', '2020.wav', '2021.wav', '2022.wav', '2023.wav', '2024.wav', '2025.wav', '2026.wav', '2027.wav', '2028.wav', '2029.wav', '2030.wav', '2031.wav', '2032.wav', '2033.wav', '2034.wav', '2035.wav', '2036.wav', '2037.wav', '2038.wav', '2039.wav', '2040.wav', '2041.wav', '2042.wav', '2043.wav', '2044.wav', '2045.wav', '2046.wav', '2047.wav', '2048.wav', '2049.wav', '2050.wav', '2051.wav', '2052.wav', '2053.wav', '2054.wav', '2055.wav', '2056.wav', '2057.wav', '2058.wav', '2059.wav', '2060.wav', '2061.wav', '2062.wav', '2063.wav', '2064.wav', '2065.wav', '2066.wav', '2067.wav', '2068.wav', '2069.wav', '2070.wav', '2071.wav', '2072.wav', '2073.wav', '2074.wav', '2075.wav', '2076.wav', '2077.wav', '2078.wav', '2079.wav', '2080.wav', '2081.wav', '2082.wav', '20

In [ ]:

import os
from pocketsphinx.pocketsphinx import *
from sphinxbase.sphinxbase import *
from pocketsphinx import *
from sphinxbase import *
from pocketsphinx.pocketsphinx import *
from sphinxbase.sphinxbase import *
from os import environ, path

MODELDIR = get_model_path()
DATADIR = get_data_path()

config = Decoder.default_config()
config.set_string('-hmm', os.path.join(MODELDIR, 'en-us/en-us'))
config.set_string('-allphone', os.path.join(MODELDIR, 'en-us/en-us-phone.lm.dmp'))
config.set_float('-lw', 2.0)
config.set_float('-beam', 1e-10)
config.set_float('-pbeam', 1e-10)

config.set_string('-hmm', path.join(MODELDIR, 'en-us'))
config.set_string('-lm', path.join(MODELDIR, 'en-us.lm.bin'))
config.set_string('-dict', path.join(MODELDIR, 'cmudict-en-us.dict'))

decoder = Decoder(config)
decoder.start_utt()

def create_phonemes_list(wav_list, phoneme_name):
  list_phonemes = list()
  for name in wav_list:
    decoder = Decoder(config)
    decoder.start_utt()
    stream = open(name, 'rb')
    while True:
      buf = stream.read(1024)
      if buf:
        decoder.process_raw(buf, False, False)
      else:
        break
    decoder.end_utt()
    hypothesis = decoder.hyp()
    print (phoneme_name + " phonemes:", [seg.word for seg in decoder.seg()])
    list_phonemes.append([seg.word for seg in decoder.seg()])
  return list_phonemes


#this takes FOREVER to run
spanish_phonemes = create_phonemes_list(spanish_list, "spanish")
english_phonemes = create_phonemes_list(english_list, "english")
german_phonemes = create_phonemes_list(german_list, "german")
japanese_phonemes = create_phonemes_list(japanese_list, "japanese")
thai_phonemes = create_phonemes_list(thai_list, "thai")


spanish phonemes: ['SIL', 'B', 'AO', 'OW', 'W', 'UH', 'IH', 'N', 'EY', 'NG', 'Y', 'UW', 'OW', 'P', 'N', 'DH', 'EH', 'SH', 'P', 'AO', 'N', 'UH', 'M', 'AH', 'T', 'R', 'UH', 'P', 'AH', 'M', 'AA', 'K', 'Z', 'SIL', 'K', 'Y', 'EH', 'NG', 'B', 'AE', 'N', 'M', 'AY', 'AH', 'DH', 'EY', 'G', 'Y', 'EY', 'DH', 'EY', 'G', 'IH', 'G', 'IH', 'NG', 'B', 'IY', 'Y', 'EH', 'AY', 'D', 'EH', 'AA', '+SPN+', 'P', 'SIL', 'IH', 'SH', 'M', 'EY', 'G', 'W', 'EY', 'N', 'AE', 'P', 'AO', 'M', 'IY', 'M', 'AY', 'L', 'EH', 'F', 'AO', 'R', 'AH', 'P', 'AO', 'N', 'AE', 'B', 'SIL', 'W', 'AH', 'N', 'D', 'IH', 'SH', 'P', 'EH', 'V', 'EH', 'V', 'R', 'P', 'AA', 'TH', 'S', 'SIL', 'SIL']
spanish phonemes: ['SIL', 'IH', 'NG', 'Y', 'EH', 'CH', 'G', 'IH', 'ZH', 'IH', 'G', 'UH', 'DH', 'EH', 'ZH', 'IH', 'N', 'EH', 'R', 'IY', 'R', 'IY', 'JH', 'G', 'R', 'N', 'EY', 'D', 'AE', 'SIL', 'SIL', 'B', 'DH', 'EH', 'N', 'N', 'IH', 'NG', 'Y', 'EH', 'T', 'B', 'AH', 'N', 'D', 'DH', 'IH', 'SH', 'T', 'OW', 'P', 'IH', 'ZH', 'UH', 'AH', 'M', 'AY', 'M', 'A

In [ ]:

import numpy as np
def get_frequencies(x, language):
    f = np.zeros(41)
    for phoneme in x:
        if phoneme == 'AA':
            f[0] += 1
        elif phoneme == 'AE':
            f[1] += 1
        elif phoneme == 'AH':
            f[2] += 1
        elif phoneme == 'AO':
            f[3] += 1
        elif phoneme == 'AW':
            f[4] += 1
        elif phoneme == 'AY':
            f[5] += 1
        elif phoneme == 'B':
            f[6] += 1
        elif phoneme == 'CH':
            f[7] += 1
        elif phoneme == 'D':
            f[8] += 1
        elif phoneme == 'DH':
            f[9] += 1
        elif phoneme == 'EH':
            f[10] += 1
        elif phoneme == 'ER':
            f[11] += 1
        elif phoneme == 'EY':
            f[12] += 1
        elif phoneme == 'F':
            f[13] += 1
        elif phoneme == 'G':
            f[14] += 1
        elif phoneme == 'HH':
            f[15] += 1
        elif phoneme == 'IH':
            f[16] += 1
        elif phoneme == 'IY':
            f[17] += 1
        elif phoneme == 'JH':
            f[18] += 1
        elif phoneme == 'K':
            f[19] += 1
        elif phoneme == 'L':
            f[20] += 1
        elif phoneme == 'M':
            f[21] += 1
        elif phoneme == 'N':
            f[22] += 1
        elif phoneme == 'NG':
            f[23] += 1
        elif phoneme == 'OW':
            f[24] += 1
        elif phoneme == 'OY':
            f[25] += 1
        elif phoneme == 'P':
            f[26] += 1
        elif phoneme == 'R':
            f[27] += 1
        elif phoneme == 'S':
            f[28] += 1
        elif phoneme == 'SH':
            f[29] += 1
        elif phoneme == 'SIL':
            f[30] += 1
        elif phoneme == 'T':
            f[31] += 1
        elif phoneme == 'TH':
            f[32] += 1
        elif phoneme == 'UH':
            f[33] += 1
        elif phoneme == 'UW':
            f[34] += 1
        elif phoneme == 'V':
            f[35] += 1
        elif phoneme == 'W':
            f[36] += 1
        elif phoneme == 'Y':
            f[37] += 1
        elif phoneme == 'Z':
            f[38] += 1
        elif phoneme == 'ZH':
            f[39] += 1

    if language == 'english':
        pass
    elif language == 'spanish':
        f[40] = 1
    elif language == 'german':
        f[40] = 2
    elif language == 'japanese':
        f[40] = 3
    elif language == 'thai':
        f[40] = 4

    return f

def create_matrix_interpreted(phoneme_list, language):
  language_interpreted = np.zeros((1,41))
  for data in phoneme_list:
    x = get_frequencies(data, language)
    language_interpreted = np.vstack([language_interpreted, x[np.newaxis,:]])
  return language_interpreted[1:, :]

spanish_matrix = create_matrix_interpreted(spanish_phonemes, 'spanish')
english_matrix = create_matrix_interpreted(english_phonemes, 'english')
german_matrix = create_matrix_interpreted(german_phonemes, 'german')
japanese_matrix = create_matrix_interpreted(japanese_phonemes, 'japanese')
thai_matrix = create_matrix_interpreted(thai_phonemes, 'thai')

#matrices
print(spanish_matrix)
print(english_matrix)
print(german_matrix)
print(japanese_matrix)
print(thai_matrix)

#matrix lengths
print(spanish_matrix.shape[0])
print(english_matrix.shape[0])
print(german_matrix.shape[0])
print(japanese_matrix.shape[0])
print(thai_matrix.shape[0])


[[3. 3. 5. ... 1. 0. 1.]
 [3. 2. 3. ... 0. 3. 1.]
 [3. 2. 4. ... 0. 2. 1.]
 ...
 [3. 5. 2. ... 0. 0. 1.]
 [4. 1. 4. ... 5. 0. 1.]
 [0. 4. 2. ... 4. 0. 1.]]
[[3. 1. 4. ... 6. 0. 0.]
 [2. 1. 8. ... 4. 1. 0.]
 [3. 2. 2. ... 0. 0. 0.]
 ...
 [5. 0. 1. ... 3. 0. 0.]
 [4. 9. 4. ... 4. 0. 0.]
 [4. 2. 2. ... 6. 0. 0.]]
[[ 7.  1. 11. ...  6.  1.  2.]
 [ 0.  1.  4. ...  0.  1.  2.]
 [ 3.  0.  8. ...  4.  1.  2.]
 ...
 [ 1.  4.  5. ...  5.  1.  2.]
 [ 3.  3. 10. ...  6.  4.  2.]
 [ 3.  3.  8. ...  5.  3.  2.]]
[[3. 0. 0. ... 1. 0. 3.]
 [3. 0. 0. ... 1. 0. 3.]
 [0. 1. 0. ... 0. 0. 3.]
 ...
 [5. 1. 3. ... 1. 0. 3.]
 [4. 1. 2. ... 2. 0. 3.]
 [4. 1. 2. ... 0. 0. 3.]]
[[4. 4. 2. ... 2. 0. 4.]
 [2. 1. 0. ... 0. 0. 4.]
 [3. 1. 2. ... 2. 0. 4.]
 ...
 [2. 0. 0. ... 1. 0. 4.]
 [0. 2. 2. ... 0. 0. 4.]
 [2. 3. 1. ... 1. 0. 4.]]
178
180
180
180
120


In [ ]:
# https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.KFold.html
from sklearn.neural_network import MLPClassifier
from sklearn.tree import DecisionTreeClassifier

dtc = DecisionTreeClassifier()
mlp = MLPClassifier()

#Allows us to do 10-fold cross validation
def ten_fold_mlp(values, targets):
  test_size = round(len(targets) / 10)

  left_cut = 0
  right_cut = 0

  train_accuracy = []
  test_accuracy = []
  for i in range(10):
    left_cut = i * test_size

    #makes it so our cut works for edge cases
    if i == 9:
      right_cut = -1
    else:
      right_cut = (i + 1) * test_size

    test_input = values[left_cut:right_cut]
    test_output = targets[left_cut:right_cut]

    input = np.concatenate((values[0:left_cut], values[right_cut + 1:]))
    output = np.concatenate((targets[0:left_cut], targets[right_cut + 1:]))


    #use your own machine learning model
    mlp.fit(input, output)

    train_accuracy.append(mlp.score(input, output))
    test_accuracy.append(mlp.score(test_input, test_output))

  return (train_accuracy, test_accuracy)

def ten_fold_dtc(values, targets):
  test_size = round(len(targets) / 10)

  left_cut = 0
  right_cut = 0

  train_accuracy = []
  test_accuracy = []
  for i in range(10):
    left_cut = i * test_size

    #makes it so our cut works for edge cases
    if i == 9:
      right_cut = -1
    else:
      right_cut = (i + 1) * test_size

    test_input = values[left_cut:right_cut]
    test_output = targets[left_cut:right_cut]

    input = np.concatenate((values[0:left_cut], values[right_cut + 1:]))
    output = np.concatenate((targets[0:left_cut], targets[right_cut + 1:]))

    #use your own machine learning model
    dtc.fit(input, output)

    train_accuracy.append(dtc.score(input, output))
    test_accuracy.append(dtc.score(test_input, test_output))

  return (train_accuracy, test_accuracy)
 
all_language_matrix = np.vstack([english_matrix, spanish_matrix, german_matrix, japanese_matrix])
np.random.shuffle(all_language_matrix)

all_language_matrix[:, :-1] = \
          (all_language_matrix[:, :-1] - np.min(all_language_matrix[:, :-1], 0)) / \
          (np.max(all_language_matrix[:, :-1], 0) - np.min(all_language_matrix[:, :-1], 0)) #normalize

train_accuracy_list_mlp, test_accuracy_list_mlp = ten_fold_mlp(all_language_matrix[:, :-1], all_language_matrix[:, -1])
train_accuracy_list_dtc, test_accuracy_list_dtc = ten_fold_dtc(all_language_matrix[:, :-1], all_language_matrix[:, -1])

avg_train_mlp = np.mean(train_accuracy_list_mlp)
avg_test_mlp = np.mean(test_accuracy_list_mlp)

print("\nMULTI-LAYER PERCEPTRON\n")
print("list of train and test accuracies")
print(train_accuracy_list_mlp, test_accuracy_list_mlp)
print("\naverage train and test accuracy")
print(avg_train_mlp, avg_test_mlp)

avg_train_dtc = np.mean(train_accuracy_list_dtc)
avg_test_dtc = np.mean(test_accuracy_list_dtc)

print("\nDECISION TREE\n")
print("list of train and test accuracies")
print(train_accuracy_list_dtc, test_accuracy_list_dtc)
print("\naverage train and test accuracy ")
print(avg_train_dtc, avg_test_dtc)




/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)



MULTI-LAYER PERCEPTRON

list of train and test accuracies
[0.9984496124031008, 0.9984496124031008, 0.9984496124031008, 1.0, 0.9984496124031008, 0.9984496124031008, 0.9984496124031008, 0.9984496124031008, 0.9984496124031008, 1.0] [1.0, 1.0, 0.9861111111111112, 0.9722222222222222, 0.9722222222222222, 0.9861111111111112, 0.9722222222222222, 0.9861111111111112, 0.9861111111111112, 1.0]

average train and test accuracy
0.9987596899224807 0.986111111111111

DECISION TREE

list of train and test accuracies
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] [0.9027777777777778, 0.8055555555555556, 0.7916666666666666, 0.9166666666666666, 0.8333333333333334, 0.8194444444444444, 0.8194444444444444, 0.875, 0.7916666666666666, 1.0]

average train and test accuracy 
1.0 0.8555555555555557


In [ ]:
uploaded = files.upload()

Saving alphabet.m4a to alphabet.m4a


In [ ]:
import os
from pocketsphinx.pocketsphinx import *
from sphinxbase.sphinxbase import *
from pocketsphinx import *
from sphinxbase import *
from pocketsphinx.pocketsphinx import *
from sphinxbase.sphinxbase import *
from os import environ, path

# #changes to wav

street = "N\ 300\ E\ St.m4a"
!ffmpeg -i La\ Playa.m4a -acodec pcm_s16le -ac 1 -ar 16000 playa.wav
!ffmpeg -i alphabet.m4a -acodec pcm_s16le -ac 1 -ar 16000 alphabet.wav
!ffmpeg -i English_test.m4a -acodec pcm_s16le -ac 1 -ar 16000 english_test.wav
!ffmpeg -i $street -acodec pcm_s16le -ac 1 -ar 16000 german_street.wav
!ffmpeg -i Domo_arigoto.m4a -acodec pcm_s16le -ac 1 -ar 16000 domo_arigoto.wav
!ffmpeg -i Danny_spanish.m4a -acodec pcm_s16le -ac 1 -ar 16000 danny_spanish.wav
!ffmpeg -i Rockford_spanish.m4a -acodec pcm_s16le -ac 1 -ar 16000 rockford_spanish.wav
!ffmpeg -i Sam\ Spanish.m4a -acodec pcm_s16le -ac 1 -ar 16000 sam_spanish.wav
!ffmpeg -i rockford_beach.m4a -acodec pcm_s16le -ac 1 -ar 16000 rockford_beach.wav

def create_phonemes(wav_file, phoneme_name):
  decoder = Decoder(config)
  decoder.start_utt()
  stream = open("playa.wav", 'rb')
  while True:
    buf = stream.read(1024)
    if buf:
      decoder.process_raw(buf, False, False)
    else:
      break
  decoder.end_utt()
  hypothesis = decoder.hyp()
  print (phoneme_name + " phonemes:", [seg.word for seg in decoder.seg()])
  return [seg.word for seg in decoder.seg()]

playa_phonemes = create_phonemes("playa.wav", "playa")
alphabet_phonemes = create_phonemes("alphabet.wav", "alphabet")
english_phonemes = create_phonemes("english_test.wav", "english test")
german_street_phonemes = create_phonemes("german_street.wav", "german street")
domo_phonemes = create_phonemes("domo_arigoto.wav", "domo")
danny_spanish = create_phonemes("danny_spanish.wav", "danny")
rockford_spanish = create_phonemes("rockford_spanish.wav", "rockford")
sam_spanish = create_phonemes("sam_spanish.wav", "sam")
beach_phonemes = create_phonemes("rockford_beach.wav", "beach")



ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lib

In [ ]:
from IPython.display import Audio
Audio(url="http://www.nch.com.au/acm/8k16bitpcm.wav")

#using nathans code and the mlp predicter to predict the language
x = get_frequencies(playa_phonemes, 'spanish')
y = get_frequencies(alphabet_phonemes, 'english')
z = get_frequencies(english_phonemes, 'english')
german_street_aud = get_frequencies(german_street_phonemes, 'german')
domo_aud = get_frequencies(domo_phonemes, 'japanese')
danny_aud = get_frequencies(danny_spanish, 'spanish')
rockford_aud = get_frequencies(rockford_spanish, 'spanish')
spanish_aud = get_frequencies(sam_spanish, 'spanish')
beach_aud = get_frequencies(beach_phonemes, 'english')

#predicting audio class

def mlp_predict():

print("playa", mlp.predict(x[:-1][np.newaxis, :]))
print("alphabet", mlp.predict(y[:-1][np.newaxis, :]))
print("english", mlp.predict(z[:-1][np.newaxis, :]))
print("german street", mlp.predict(german_street_aud[:-1][np.newaxis, :]))
print("japanese", mlp.predict(domo_aud[:-1][np.newaxis, :]))
print("danny", mlp.predict(danny_aud[:-1][np.newaxis, :]))
print("rockford spanish", mlp.predict(rockford_aud[:-1][np.newaxis, :]))
print("sam spanish", mlp.predict(spanish_aud[:-1][np.newaxis, :]))
print("beach phonemes", mlp.predict(beach_aud[:-1][np.newaxis, :]))

# Audio(url="danny_spanish.wav")
# Audio(url="alphabet.wav")





playa [1.]
alphabet [1.]
english [1.]
german street [1.]
japanese [1.]
danny [1.]
rockford spanish [1.]
sam spanish [1.]
beach phonemes [1.]


# for f in file_list:
#   # 3. Create & download by id.
#   print('title: %s, id: %s' % (f['title'], f['id']))
#   fname = os.path.join(local_download_path, f['title'])
#   print('downloading to {}'.format(fname))
#   f_ = drive.CreateFile({'id': f['id']})
#   f_.GetContentFile(fname)
#   list_files.append(f_.GetContentFile(fname))
#   list_f_.append(f_)

# with open(fname, 'r') as f:
#   print(f.read())


# config = {
#     'verbose': False,
#     'audio_file': os.path.join(data_path, 'goforward.raw'),
#     'buffer_size': 2048,
#     'no_search': False,
#     'full_utt': False,
#     'hmm': os.path.join(model_path, 'en-us'),
#     'lm': os.path.join(model_path, 'en-us.lm.bin'),
#     'dict': os.path.join(model_path, 'cmudict-en-us.dict')
# }

Garbage code that we might need later